In [1]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

In [2]:
x = np.load('./tatanic_X_train.npy')
y = np.load('./tatanic_y_train.npy')

In [3]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = \
    train_test_split(x, y, test_size = 0.3, random_state = 11)

In [4]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(622, 27)
(267, 27)
(622,)
(267,)


In [5]:
x_train[0]

array([0.29850933, 0.48312843, 0.11111111, 0.        , 0.        ,
       0.        , 0.5       , 1.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [6]:
y_train[:10]

array([0., 1., 0., 1., 0., 0., 0., 0., 0., 0.])

In [7]:
x_test[0]

array([0.52398848, 0.05074862, 0.        , 0.5       , 1.        ,
       0.125     , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [8]:
y_test[:10]

array([1., 0., 0., 1., 0., 0., 0., 1., 1., 0.])

In [12]:
clf2 = DecisionTreeClassifier(random_state = 1)
eclf = BaggingClassifier(clf2, oob_score = True)

In [14]:
clf2.fit(x_train, y_train)
preds = clf2.predict(x_test)
clf2.score(x_test, y_test)

0.7827715355805244

In [15]:
eclf.fit(x_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:615: RuntimeWarning: invalid value encountered in true_divide
  predictions.sum(axis=1)[:, np.newaxis])


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=None, oob_score=True,
         random_state=None, verbose=0, warm_start=False)

In [16]:
predictions = eclf.predict(x_test)

In [17]:
eclf.score(x_test, y_test)

0.8239700374531835

In [18]:
from sklearn.metrics import confusion_matrix, classification_report

In [19]:
# confusion_matrix for BaggingClassifier
confusion_matrix(y_test, predictions)

array([[141,  20],
       [ 27,  79]], dtype=int64)

In [22]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.84      0.88      0.86       161
         1.0       0.80      0.75      0.77       106

   micro avg       0.82      0.82      0.82       267
   macro avg       0.82      0.81      0.81       267
weighted avg       0.82      0.82      0.82       267



In [24]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, x, y, cv = 5).mean()
# cv = 5 : 다섯번 돌아가면서 각각 테스트값을 리턴

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:615: RuntimeWarning: invalid value encountered in true_divide
  predictions.sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:615: RuntimeWarning: invalid value encountered in true_divide
  predictions.sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probabl

0.806576525106329

In [25]:
# parameter bagging parameter
params ={
    "n_estimators" : [10,20,30,40,50,55], # estimator
    "max_samples" : [0.5,0.6,0.7,0.8,0.9,1] # sample
}

In [28]:
# ensemble(BaggingClassifier) + overfittingtunning(CV,GSCV) +
# crossval(CV) + paramtunning(GridSearchCV) ->

# quiz - gridsearch operation

from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(estimator= eclf, param_grid = params, cv = 5)
grid.fit(x_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:615: RuntimeWarning: invalid value encountered in true_divide
  predictions.sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:615: RuntimeWarning: invalid value encountered in true_divide
  predictions.sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probabl

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            ...estimators=10, n_jobs=None, oob_score=True,
         random_state=None, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_estimators': [10, 20, 30, 40, 50, 55], 'max_samples': [0.5, 0.6, 0.7, 0.8, 0.9, 1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [29]:
grid.best_score_

0.7958199356913184

In [30]:
grid.best_params_

{'max_samples': 0.5, 'n_estimators': 55}

In [31]:
grid.best_estimator_.oob_score_

0.8054662379421221

In [32]:
grid.best_estimator_

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=0.5, n_estimators=55, n_jobs=None, oob_score=True,
         random_state=None, verbose=0, warm_start=False)

In [37]:
pred = grid.predict(x_test)

In [38]:
# confusion matrix

confusion_matrix(y_test, pred)

array([[144,  17],
       [ 23,  83]], dtype=int64)

In [39]:
# classification_report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

         0.0       0.86      0.89      0.88       161
         1.0       0.83      0.78      0.81       106

   micro avg       0.85      0.85      0.85       267
   macro avg       0.85      0.84      0.84       267
weighted avg       0.85      0.85      0.85       267



In [40]:
grid.score(x_test, y_test)

0.850187265917603