In [1]:
import numpy as np

In [2]:
x = np.load("./tatanic_X_train.npy")
y = np.load("./tatanic_y_train.npy")

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = \
    train_test_split(x, y, test_size = 0.3, random_state = 11)

In [4]:
x_train[0]

array([0.29850933, 0.48312843, 0.11111111, 0.        , 0.        ,
       0.        , 0.5       , 1.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [5]:
y_train[:10]

array([0., 1., 0., 1., 0., 0., 0., 0., 0., 0.])

In [6]:
from sklearn.ensemble import RandomForestClassifier
eclf = RandomForestClassifier(n_estimators = 100,
                              max_features = 2,
                              n_jobs = 7,
                              oob_score = True)

In [7]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, x_train, y_train, cv = 5).mean()

0.766818882769473

In [9]:
 params ={
    "n_estimators" : [10, 20, 30, 50, 100],
    "max_features" : [1,2,3,4,5,6,7, 10, 15, 20, 25, len(x[0])]
    }

In [11]:
# cross_val_score - cross validation
# GridSearchCV - cross validation, parm grid search, model return

# gridsearchcv operation

from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(estimator = eclf, param_grid = params, cv = 5)
grid.fit(x_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means t

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means t

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means t

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means t

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=2, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=7,
            oob_score=True, random_state=None, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_estimators': [10, 20, 30, 50, 100], 'max_features': [1, 2, 3, 4, 5, 6, 7, 10, 15, 20, 25, 27]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [12]:
grid.best_score_

0.7990353697749196

In [14]:
grid.best_params_

{'max_features': 7, 'n_estimators': 10}

In [16]:
grid.best_estimator_.oob_score_

0.7620578778135049

In [17]:
grid.best_estimator_

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=7, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=7,
            oob_score=True, random_state=None, verbose=0, warm_start=False)

In [18]:
pred = grid.predict(x_test)

In [19]:
from sklearn.metrics import confusion_matrix, classification_report

In [20]:
# confusion matrix

confusion_matrix(y_test, pred)

array([[136,  25],
       [ 22,  84]], dtype=int64)

In [21]:
# classification report
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

         0.0       0.86      0.84      0.85       161
         1.0       0.77      0.79      0.78       106

   micro avg       0.82      0.82      0.82       267
   macro avg       0.82      0.82      0.82       267
weighted avg       0.82      0.82      0.82       267



In [22]:
btree = RandomForestClassifier(max_features = 20, n_estimators = 20)

In [23]:
btree.fit(x_train, y_train)
btree.score(x_test, y_test)

0.8614232209737828

In [24]:
btree.feature_importances_

array([2.29669226e-01, 2.17146153e-01, 2.37131328e-02, 9.87138174e-02,
       1.29800796e-01, 4.11893730e-02, 1.42294793e-02, 1.08935766e-02,
       1.09181539e-02, 1.79636600e-02, 1.82754090e-03, 3.00820854e-04,
       1.13170785e-03, 1.19689087e-02, 5.01345759e-03, 1.36068622e-01,
       6.69517269e-03, 4.06503970e-03, 1.11924311e-02, 2.29290032e-03,
       3.33151469e-03, 5.63653086e-03, 7.22719849e-03, 6.29382781e-03,
       1.70413863e-03, 8.02152754e-04, 2.10666592e-04])