### 0.0.1 The Boston Housing Dataset

* https://archive.ics.uci.edu/ml/datasets/Housing

In [1]:
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import numpy as np

In [2]:
boston = load_boston()
boston["data"]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [5]:
x_data = boston.data
y_data = boston.target.reshape(boston.target.size, 1)

In [6]:
y_data.shape

(506, 1)

In [14]:
from sklearn import preprocessing

minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 5)).fit(x_data)
# standard_scale = preprocessing.StandardScaler().fit(x_data)

x_scaled_data = minmax_scale.transform(x_data)

x_scaled_data[:3]


array([[0.00000000e+00, 9.00000000e-01, 3.39076246e-01, 0.00000000e+00,
        1.57407407e+00, 2.88752635e+00, 3.20803296e+00, 1.34601570e+00,
        0.00000000e+00, 1.04007634e+00, 1.43617021e+00, 5.00000000e+00,
        4.48399558e-01],
       [1.17961270e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 2.73998850e+00, 3.91349125e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 5.00000000e+00,
        1.02235099e+00],
       [1.17848872e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 3.47192949e+00, 2.99691040e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 4.94868627e+00,
        3.17328918e-01]])

In [44]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_scaled_data, y_data, test_size = 0.33)

In [45]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((339, 13), (167, 13), (339, 1), (167, 1))

In [46]:
from sklearn import linear_model

regr = linear_model.LinearRegression(fit_intercept = True, # fit_intercept = True 면 절편이 있고(ax + b), False면 절편이 없다(ax).
                                    normalize = False, # 스케일링 , 앞에서 해줘서 False로
                                    copy_X = True,  # Copy 하겠냐
                                    n_jobs = 8 ) # 사용할 Cpu의 갯수, -1이면 사용가능한 최대한 사용

regr.fit(x_train, y_train)
regr

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=8, normalize=False)

In [47]:
regr.coef_ , regr.intercept_

(array([[-0.84133877,  0.6952572 ,  0.22041095,  0.87510054, -1.92496658,
          4.51061001, -0.17908231, -3.41315706,  1.141962  , -1.07052672,
         -1.71044365,  0.77053335, -3.50364824]]), array([25.21562861]))

In [56]:
# The coefficients

print('coefficients : ', regr.coef_)
print('intercept : ', regr.intercept_)

coefficients :  [[-0.84133877  0.6952572   0.22041095  0.87510054 -1.92496658  4.51061001
  -0.17908231 -3.41315706  1.141962   -1.07052672 -1.71044365  0.77053335
  -3.50364824]]
intercept :  [25.21562861]


In [49]:
regr.predict(x_data[:5])

array([[-12.30747424],
       [ 10.29959252],
       [ 31.70095225],
       [ 55.01780396],
       [ 47.53012457]])

In [50]:
x_data[:5].dot(regr.coef_.T) + regr.intercept_

array([[-12.30747424],
       [ 10.29959252],
       [ 31.70095225],
       [ 55.01780396],
       [ 47.53012457]])

In [51]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [52]:
y_true = y_test
y_hat = regr.predict(x_test)

r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat), mean_squared_error(y_true, y_hat)

(0.7496739098520244, 3.135142620527438, 20.25293063413967)

In [53]:
y_true = y_train

y_hat = regr.predict(x_train)

r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat), mean_squared_error(y_true, y_hat)

(0.7270454829456481, 3.4361815198436707, 23.503676602364543)

In [54]:
regr.score(x_test, y_test)

0.7496739098520244