### numpy 모듈의 호출

In [2]:
import numpy as np

### array의 생성

In [2]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

In [4]:
type(test_array[3])

numpy.float64

In [5]:
test_array = np.array([1,4,5,"8"], float)
test_array

array([1., 4., 5., 8.])

In [6]:
type(test_array[3])

numpy.float64

In [7]:
test_array.dtype

dtype('float64')

In [8]:
test_array

array([1., 4., 5., 8.])

In [9]:
test_array.shape

(4,)

### array shape

In [10]:
vector = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [11]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [3]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(5, 3, 4)

In [14]:
np.array(tensor,int).ndim

3

In [15]:
np.array(tensor, int).size

48

### numpy dtype

In [13]:
np.array([[1,2,3],[4.5,5,6]], dtype=np.int32).nbytes

24

In [17]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [18]:
np.array([[1,2,3],[4.5,"5","7"]], dtype=np.float32).nbytes

24

In [24]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.int8).nbytes

6

In [20]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float64).nbytes

48