In [3]:
import numpy as np

### Array operations

In [2]:
test_a = np.array([[1,2,3],[4,5,6]], float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
test_a + test_a 

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [4]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [6]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

### dot product

In [8]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)

In [9]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [11]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [12]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [16]:
test_a.dot(test_a.T)

array([[14, 32],
       [32, 77]])

### broadcasting

In [10]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3
test_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [36]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [37]:
test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [38]:
test_matrix / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [12]:
test_matrix // 0.2

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [25]:
test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
print(test_matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
print(test_vector)

[10 20 30]


In [32]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### numpy performance

In [42]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iternation_max = 100000000
vector = list(range(iternation_max))
scalar = 2

In [47]:
%timeit scalar_vector_product(scalar, vector) # for loop

12.8 s ± 977 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [48]:
%timeit [scalar * value for value in range(iternation_max)] # list comprehension

11.1 s ± 136 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [49]:
%timeit np.arange(iternation_max) * scalar # numpy

451 ms ± 2.73 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


4.0