In [14]:
import numpy as np

In [15]:
weight_vector = np.array([[1], [1], [1]]) # Weight Vector
x_vector = np.array([[3], [4], [5]])

In [16]:
weight_vector.T.dot(x_vector)

array([[12]])

In [17]:
import pandas as pd

In [18]:
data_url = 'data/housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header = None)
df_data.columns = ['CRIM', 'ZN', "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT", "MEDV"]
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [19]:
df_data['weight_0'] = 1
df_data = df_data.drop("MEDV", axis=1)
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98         1  
1     17.8  396.90   9.14         1  
2     17.8  392.83   4.03         1  
3     18.7  394.63   2.94         1  
4     18.7  396.90   5.33         1

In [20]:
df_matrix = df_data.as_matrix()
weight_vector = np.random.random_sample((14, 1))

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [25]:
df_matrix.dot(weight_vector)

array([[393.43780036],
       [367.44090624],
       [347.23534869],
       [319.82365409],
       [329.48186489],
       [332.84527962],
       [410.42755595],
       [442.02324725],
       [449.10098531],
       [429.46100795],
       [440.34920194],
       [426.78616045],
       [385.33727555],
       [401.06289713],
       [418.88847174],
       [395.8031596 ],
       [367.79493903],
       [420.28672471],
       [352.7924917 ],
       [407.79206867],
       [436.4421559 ],
       [428.05532358],
       [434.35633431],
       [441.97877541],
       [434.56622536],
       [404.87334469],
       [426.13145442],
       [408.98673551],
       [431.47194119],
       [422.6066998 ],
       [429.83005763],
       [434.28218404],
       [390.3848685 ],
       [427.71449513],
       [404.01702592],
       [385.05277331],
       [375.02344617],
       [360.26330571],
       [349.71132747],
       [343.26898742],
       [336.46658337],
       [286.54101767],
       [289.98052361],
       [293

In [26]:
df_data.values.dot(weight_vector)

array([[393.43780036],
       [367.44090624],
       [347.23534869],
       [319.82365409],
       [329.48186489],
       [332.84527962],
       [410.42755595],
       [442.02324725],
       [449.10098531],
       [429.46100795],
       [440.34920194],
       [426.78616045],
       [385.33727555],
       [401.06289713],
       [418.88847174],
       [395.8031596 ],
       [367.79493903],
       [420.28672471],
       [352.7924917 ],
       [407.79206867],
       [436.4421559 ],
       [428.05532358],
       [434.35633431],
       [441.97877541],
       [434.56622536],
       [404.87334469],
       [426.13145442],
       [408.98673551],
       [431.47194119],
       [422.6066998 ],
       [429.83005763],
       [434.28218404],
       [390.3848685 ],
       [427.71449513],
       [404.01702592],
       [385.05277331],
       [375.02344617],
       [360.26330571],
       [349.71132747],
       [343.26898742],
       [336.46658337],
       [286.54101767],
       [289.98052361],
       [293